# Name of Spring Application
spring.application.name=3A-EcommerceApi-UndirectionalRelations-h2DB
# Changes default port from 8080 to 8082 to avoid conflict
server.port=8082

# H2 persistent database - file based (data survives app restart)
spring.datasource.url=jdbc:h2:file:./data/ecommerce_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

# Tells Spring which driver class to load (different drivers for different DB)
spring.datasource.driverClassName=org.h2.Driver

# H2 database credentials
spring.datasource.username=sa
spring.datasource.password=

# Tells Hibernate which SQL dialect to generate (different databases have different SQL syntax)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Schema generation strategy - "update" keeps existing data when app restarts
spring.jpa.hibernate.ddl-auto=update

# Enables H2's web based DBMS UI
spring.h2.console.enabled=true

# Custom path for web based DBMS UI
spring.h2.console.path=/h2-console

# Prints generated SQL queries to console
spring.jpa.show-sql=true

# Pretty-prints SQL in console
spring.jpa.properties.hibernate.format_sql=true

# Shows actual SQL parameter values (remove if too verbose)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE