# Name of Spring Application
spring.application.name=2-RestApi-h2-DB
# Changes default port from 8080 to 8081 to avoid conflict
server.port = 8081
# using h2 database which is in-memory
spring.datasource.url=jdbc:h2:mem:testdb
# tells spring which driver class to load (different drivers for different db i.e MySQl,MongoDB, ... etc)
spring.datasource.driverClassName=org.h2.Driver
# tells hibernate which SQL dialect to generate(different databases have different SQL syntax)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# enables h2's web based dbms ui
spring.h2.console.enabled=true
# custom path for web based dbms ui
spring.h2.console.path=/h2-console
#prints generated SQL queries to console
spring.jpa.show-sql=true 
